<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RealEstateManagement.PropertyManagement.Domain\RealEstateManagement.PropertyManagement.Domain.csproj" />
    <ProjectReference Include="..\RealEstateManagement.PropertyManagement.Application\RealEstateManagement.PropertyManagement.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\RealEstateManagement.BuildingBlocks.Infrastructure\RealEstateManagement.BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageReference Include="Quartz" Version="3.15.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
